export default {
    arrayNameTheoryJs: [
        "template-item",
        "Console",
        "Variable",
        "Data types",
        "If Else",
        "Switch",
        "While",
        "Do While",
        "For",
        "API",
        "Destructuring",
        "Arrow function",
        "JSON",
        "HTMLElement-hidden",
        "Date",
        "Try Catch",
        "Cookies",
        "Local Storage",
        "Networking REST API",
        "Fetch",
        "Math",
        "Regular expressions",
        "Send form with fetch",
        "Form Data",
        "Rendering",
        "Methods for Array",
        "For of",
        "Spread REST operators",
        "Class",
        "Mock",
        "Pagination",
        "Map Set",
        "Object assign"
    ],
};
